// <auto-generated />
namespace big_school_ntk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class populatecategorytable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populatecategorytable));
        
        string IMigrationMetadata.Id
        {
            get { return "202203180815112_populatecategorytable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
